spring:
  datasource:
    url: jdbc:mysql://${mysql.host:192.168.0.160}:${mysql.port:3316}/${mysql.database:registration_system}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${mysql.username:root}
    password: ${mysql.password:Bar888888}
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

---
spring:
  config:
    activate:
      on-profile: local
mysql:
  host: 192.168.0.160
  port: 3316
  database: registration_system
  username: root
  password: Bar888888

---
spring:
  config:
    activate:
      on-profile: test
mysql:
  host: localhost
  port: 3306
  database: registration_system
  username: root
  password: beifa888

---
spring:
  config:
    activate:
      on-profile: prod
mysql:
  host: 192.168.0.160
  port: 3316
  database: registration_system
  username: root
  password: Bar888888
